apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=ExternalArtifact=true

resources:
  - namespace.yaml
  - upstream/manifests/source-controller.yaml
  - upstream/manifests/source-watcher.yaml
  - upstream/manifests/kustomize-controller.yaml
  - upstream/manifests/notification-controller.yaml
  - upstream/manifests/policies.yaml
  - upstream/manifests/rbac.yaml


